import Link from 'next/link';
import { Navbar } from '@/components/navbar';
import { Footer } from '@/components/footer';

export const metadata = {
  title: 'Terms of Service - CortexAmp',
  description: 'Terms of Service for CortexAmp',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      
      <main className="flex-1 container mx-auto px-4 py-20 max-w-4xl">
        <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
        <div className="prose prose-invert max-w-none space-y-6">
          <p className="text-muted-foreground">Last updated: December 22, 2024</p>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">1. Acceptance of Terms</h2>
            <p>
              By accessing and using CortexAmp, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to these terms, please do not use our service.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">2. Description of Service</h2>
            <p>
              CortexAmp provides daily AI learning challenges with automated feedback. Our service includes:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Daily AI challenges across multiple learning tracks</li>
              <li>AI-generated feedback on your submissions</li>
              <li>Progress tracking and streak monitoring</li>
              <li>Access to challenge history</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">3. AI-Generated Content Disclaimer</h2>
            <p>
              <strong>Important:</strong> All feedback provided by CortexAmp is generated by artificial intelligence. While we strive for accuracy and helpfulness, AI-generated feedback:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>May contain errors or inaccuracies</li>
              <li>Should be reviewed critically before relying on it</li>
              <li>Does not constitute professional advice</li>
              <li>Is provided for educational purposes only</li>
            </ul>
            <p>
              You are responsible for evaluating and verifying any AI-generated feedback before applying it to real-world situations.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">4. User Accounts</h2>
            <p>
              You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Provide accurate and complete information</li>
              <li>Keep your password secure</li>
              <li>Notify us immediately of any unauthorized use</li>
              <li>Use the service in compliance with all applicable laws</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">5. User Content</h2>
            <p>
              You retain ownership of any content you submit to CortexAmp. By submitting content, you grant us a license to use, store, and process your submissions for the purpose of providing our service and improving our AI models.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">6. Prohibited Uses</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Use the service for any illegal purpose</li>
              <li>Attempt to gain unauthorized access to our systems</li>
              <li>Interfere with or disrupt the service</li>
              <li>Share your account with others</li>
              <li>Use automated systems to access the service</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">7. Limitation of Liability</h2>
            <p>
              CortexAmp is provided &quot;as is&quot; without warranties of any kind. We are not liable for any damages arising from your use of the service, including but not limited to:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Errors or inaccuracies in AI-generated feedback</li>
              <li>Loss of data or progress</li>
              <li>Service interruptions or downtime</li>
              <li>Any decisions made based on our content</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">8. Changes to Terms</h2>
            <p>
              We reserve the right to modify these terms at any time. We will notify users of significant changes via email or through the service. Continued use of CortexAmp after changes constitutes acceptance of the new terms.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">9. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your account at any time for violation of these terms or for any other reason at our discretion.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">10. Governing Law</h2>
            <p>
              These terms shall be governed by and construed in accordance with the laws of the United States, without regard to its conflict of law provisions.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">11. Contact</h2>
            <p>
              If you have questions about these Terms of Service, please contact us at: <a href="mailto:support@cortexamp.com" className="text-primary hover:underline">support@cortexamp.com</a>
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t">
          <Link href="/" className="text-primary hover:underline">
            ← Back to Home
          </Link>
        </div>
      </main>

      <Footer />
    </div>
  );
}
