-- Migration: Add challenge deduplication fields
-- Prevents duplicate challenges when scaling with AI generation

-- Add canonical_goal and challenge_fingerprint columns
ALTER TABLE challenges ADD COLUMN IF NOT EXISTS canonical_goal text;
ALTER TABLE challenges ADD COLUMN IF NOT EXISTS challenge_fingerprint text;
ALTER TABLE challenges ADD COLUMN IF NOT EXISTS generated_by_ai boolean DEFAULT false;
ALTER TABLE challenges ADD COLUMN IF NOT EXISTS reviewed_by_human boolean DEFAULT false;

-- Add unique constraint on fingerprint to prevent exact duplicates
-- Drop constraint if it exists first (idempotent)
ALTER TABLE challenges DROP CONSTRAINT IF EXISTS unique_challenge_fingerprint;
ALTER TABLE challenges ADD CONSTRAINT unique_challenge_fingerprint UNIQUE (challenge_fingerprint);

-- Create index for faster duplicate lookups
CREATE INDEX IF NOT EXISTS idx_challenges_fingerprint ON challenges(challenge_fingerprint);
CREATE INDEX IF NOT EXISTS idx_challenges_canonical_goal ON challenges(canonical_goal);

-- Backfill existing challenges with fingerprints based on title + scenario
-- This is a simple hash for existing data; new challenges should use proper canonical goals
UPDATE challenges
SET 
  canonical_goal = LOWER(TRIM(title)),
  challenge_fingerprint = encode(sha256(LOWER(TRIM(title))::bytea), 'hex')
WHERE canonical_goal IS NULL OR challenge_fingerprint IS NULL;

-- Add NOT NULL constraints after backfill
ALTER TABLE challenges ALTER COLUMN canonical_goal SET NOT NULL;
ALTER TABLE challenges ALTER COLUMN challenge_fingerprint SET NOT NULL;

-- Add comments for documentation
COMMENT ON COLUMN challenges.canonical_goal IS 'Normalized, short sentence describing the core goal of the challenge';
COMMENT ON COLUMN challenges.challenge_fingerprint IS 'SHA256 hash of canonical_goal for deterministic duplicate detection';
COMMENT ON COLUMN challenges.generated_by_ai IS 'True if challenge was generated by AI, false if created by human';
COMMENT ON COLUMN challenges.reviewed_by_human IS 'True if challenge has been reviewed and approved by human admin';
